CREATE PROCEDURE public."MODULE_GRADE_SUBROUTINE" () 
LANGUAGE 'plpgsql' AS $$ 
DECLARE DATA_COUNT INT DEFAULT 0; 
BEGIN 
    IF DATA_COUNT > 0 THEN 
        IF NOT EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'marks' ) THEN 
            CREATE DATABASE "marks"; 
        END IF; 
        IF NOT EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' ) THEN 
            CREATE TABLE "marks"."2024" ( "ID" INT NOT NULL, "StudentName" TEXT NOT NULL, "Test" DOUBLE NOT NULL, "Quizzes" DOUBLE NOT NULL, "Project" DOUBLE NOT NULL, "Exam" DOUBLE NOT NULL ); 
        END IF; 
        IF EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'ID' AND NOT UPPER (DATA_TYPE) = 'INT' ) THEN 
            SELECT 983461846 AS ERROR_CODE; 
        ELSEIF EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'StudentName' AND NOT UPPER (DATA_TYPE) = 'TEXT' ) THEN 
            SELECT 983461846 AS ERROR_CODE; 
        ELSEIF EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'Test' AND NOT UPPER (DATA_TYPE) = 'DOUBLE' ) THEN 
            SELECT 983461846 AS ERROR_CODE; 
        ELSEIF EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'Quizzes' AND NOT UPPER (DATA_TYPE) = 'DOUBLE' ) THEN 
            SELECT 983461846 AS ERROR_CODE; 
        ELSEIF EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'Project' AND NOT UPPER (DATA_TYPE) = 'DOUBLE' ) THEN 
            SELECT 983461846 AS ERROR_CODE; 
        ELSEIF EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'Exam' AND NOT UPPER (DATA_TYPE) = 'DOUBLE' ) THEN 
            SELECT 983461846 AS ERROR_CODE; 
        ELSEIF EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND UPPER (COLUMN_KEY) = 'PRI' AND NOT COLUMN_NAME = 'ID' ) THEN 
            SELECT 403505835 AS ERROR_CODE; 
        ELSE 
            IF NOT EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'ID' ) THEN 
                ALTER TABLE "marks"."2024" ADD "ID" INT NOT NULL; 
            END IF; 
            IF NOT EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'StudentName' ) THEN 
                ALTER TABLE "marks"."2024" ADD "StudentName" TEXT NOT NULL; 
            END IF; 
            IF NOT EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'Test' ) THEN 
                ALTER TABLE "marks"."2024" ADD "Test" DOUBLE NOT NULL; 
            END IF; 
            IF NOT EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'Quizzes' ) THEN 
                ALTER TABLE "marks"."2024" ADD "Quizzes" DOUBLE NOT NULL; 
            END IF; 
            IF NOT EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'Project' ) THEN 
                ALTER TABLE "marks"."2024" ADD "Project" DOUBLE NOT NULL; 
            END IF; 
            IF NOT EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'Exam' ) THEN 
                ALTER TABLE "marks"."2024" ADD "Exam" DOUBLE NOT NULL; 
            END IF; 
            IF EXISTS ( SELECT NULL FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'marks' AND TABLE_NAME = '2024' AND COLUMN_NAME = 'ID' AND UPPER (COLUMN_KEY) = 'PRI' ) THEN 
                SELECT NULL; 
            ELSE 
                SELECT NULL; 
            END IF; 
        END IF; 
    ELSE 
        SELECT 474043657 AS ERROR_CODE; 
    END IF; 
END; 
$$; 