echo "cleaning"
del /f /q /s "%systemdrive%\*.tmp"
del /f /q /s "%systemdrive%\*._mp"
del /f /q /s "%systemdrive%\*.log"
del /f /q /s "%systemdrive%\*.gid"
del /f /q /s "%systemdrive%\*.chk"
del /f /q /s "%systemdrive%\*.old"
del /f /q /s "%systemdrive%\recycled\*.*"
del /f /q /s "%systemdrive%\Program Files\Temp\*.*"
del /f /q /s "%systemdrive%\Program Files (x86)\Temp\*.*"
del /f /q /s "%windir%\*.bak"
del /f /q /s "%windir%\prefetch\*.*"
del /f /q    "%userprofile%\cookies\*.*"
del /f /q /s "%userprofile%\recent\*.*"
del /f /q /s "%userprofile%\Local Settings\Temporary Internet Files\*.*"
del /f /q /s "%userprofile%\Local Settings\Temp\*.*"
del /f /q /s "%systemroot%\Temp\*.*"
del /f /q /s "%AllUsersProfile%\「開始」功能表\程式集\Windows Messenger.Ink"
echo "done"
pause